# coding: utf-8

"""
    AdvoService Integration API

    External API for AdvoService  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: r.starenkiy@kf.ua
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CertificateUserDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'phone': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'email': 'str',
        'locality': 'str',
        'address': 'str',
        'certificate_code': 'str'
    }

    attribute_map = {
        'phone': 'phone',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'email': 'email',
        'locality': 'locality',
        'address': 'address',
        'certificate_code': 'certificate_code'
    }

    def __init__(self, phone=None, first_name=None, last_name=None, email=None, locality=None, address=None, certificate_code=None):  # noqa: E501
        """CertificateUserDetails - a model defined in OpenAPI"""  # noqa: E501

        self._phone = None
        self._first_name = None
        self._last_name = None
        self._email = None
        self._locality = None
        self._address = None
        self._certificate_code = None
        self.discriminator = None

        if phone is not None:
            self.phone = phone
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if email is not None:
            self.email = email
        if locality is not None:
            self.locality = locality
        if address is not None:
            self.address = address
        self.certificate_code = certificate_code

    @property
    def phone(self):
        """Gets the phone of this CertificateUserDetails.  # noqa: E501

        Телефон пользователя  # noqa: E501

        :return: The phone of this CertificateUserDetails.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this CertificateUserDetails.

        Телефон пользователя  # noqa: E501

        :param phone: The phone of this CertificateUserDetails.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def first_name(self):
        """Gets the first_name of this CertificateUserDetails.  # noqa: E501

        Имя пользователя  # noqa: E501

        :return: The first_name of this CertificateUserDetails.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this CertificateUserDetails.

        Имя пользователя  # noqa: E501

        :param first_name: The first_name of this CertificateUserDetails.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this CertificateUserDetails.  # noqa: E501

        Фамилия пользователя  # noqa: E501

        :return: The last_name of this CertificateUserDetails.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this CertificateUserDetails.

        Фамилия пользователя  # noqa: E501

        :param last_name: The last_name of this CertificateUserDetails.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this CertificateUserDetails.  # noqa: E501

        Email пользователя  # noqa: E501

        :return: The email of this CertificateUserDetails.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this CertificateUserDetails.

        Email пользователя  # noqa: E501

        :param email: The email of this CertificateUserDetails.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def locality(self):
        """Gets the locality of this CertificateUserDetails.  # noqa: E501

        Город пользователя  # noqa: E501

        :return: The locality of this CertificateUserDetails.  # noqa: E501
        :rtype: str
        """
        return self._locality

    @locality.setter
    def locality(self, locality):
        """Sets the locality of this CertificateUserDetails.

        Город пользователя  # noqa: E501

        :param locality: The locality of this CertificateUserDetails.  # noqa: E501
        :type: str
        """

        self._locality = locality

    @property
    def address(self):
        """Gets the address of this CertificateUserDetails.  # noqa: E501

        Адрес пользователя (без города)  # noqa: E501

        :return: The address of this CertificateUserDetails.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this CertificateUserDetails.

        Адрес пользователя (без города)  # noqa: E501

        :param address: The address of this CertificateUserDetails.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def certificate_code(self):
        """Gets the certificate_code of this CertificateUserDetails.  # noqa: E501

        Код сертификата  # noqa: E501

        :return: The certificate_code of this CertificateUserDetails.  # noqa: E501
        :rtype: str
        """
        return self._certificate_code

    @certificate_code.setter
    def certificate_code(self, certificate_code):
        """Sets the certificate_code of this CertificateUserDetails.

        Код сертификата  # noqa: E501

        :param certificate_code: The certificate_code of this CertificateUserDetails.  # noqa: E501
        :type: str
        """
        if certificate_code is None:
            raise ValueError("Invalid value for `certificate_code`, must not be `None`")  # noqa: E501

        self._certificate_code = certificate_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CertificateUserDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
