
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-30T09:46:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "570b70ecb6f99af0e3842bab12c3a1cb7d3b6928",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
