
'''
This file is automatically generated; Do not edit it. :)
'''
VERSION_INFO = {
    'final': True,
    'version': '1.19.7.post1',
    'branch_nick': '(HEAD',
    'revision_id': '6d595b3bbad61822e2fad178e805b3ecf919f626',
    'revno': 8003
}
