# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-04-19T21:35:46.915133'

__version__ = '2019.4.4'
__sha__ = '746d990986b3302fdb4fccb55dbc426a6d7e9a6a'
__revision__ = '746d990986b3302fdb4fccb55dbc426a6d7e9a6a'
