# -*- coding: utf-8 -*-

"""
    stupidpackage

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class OAuthScopeEnum(object):

    """Implementation of the 'OAuth Scope' enum.

    OAuth 2 scopes supported by the API

    Attributes:
        WRITEPETS: modify pets in your account
        READPETS: read your pets

    """

    WRITEPETS = 'write:pets'

    READPETS = 'read:pets'

