# -*- coding: utf-8 -*-

"""
    stupidpackage

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class Status6Enum(object):

    """Implementation of the 'Status6' enum.

    TODO: type enum description here.

    Attributes:
        AVAILABLE: TODO: type description here.
        PENDING: TODO: type description here.
        SOLD: TODO: type description here.

    """

    AVAILABLE = 'available'

    PENDING = 'pending'

    SOLD = 'sold'

