
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-30T14:07:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d119eed55e15bb5cb221f8e0287b9f547ec9fc20",
 "version": "v0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
