# -*- coding: utf-8 -*-

"""
    demobambu

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from demobambu.api_helper import APIHelper
from demobambu.configuration import Configuration
from demobambu.controllers.base_controller import BaseController

class MiscController(BaseController):

    """A Controller to access Endpoints in the demobambu API."""


    def get_expense_estimator(self):
        """Does a GET request to /.

        TODO: Add Description

        Returns:
            void: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _url_path = '/'
        _query_builder = Configuration.get_base_uri()
        _query_builder += _url_path
        _query_url = APIHelper.clean_url(_query_builder)

        # Prepare and execute request
        _request = self.http_client.get(_query_url)
        _context = self.execute_request(_request)
        self.validate_response(_context)
