
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-05T15:12:32-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d29b0a9a1abc7e8aa7d3e3b50b9d64adcacc1a4",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
