
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-15T19:24:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "122ae2b08e1038d483e4e7e5769c512fe9554142",
 "version": "0.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
