
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-30T17:42:29-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "75b23c94fb0b5d339efdba2ef67b9b55a13251aa",
 "version": "v0.2.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
