
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "266733585e4b3b9fd86da40fd050ee9e59718183",
 "version": "2126"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
