
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-03T09:53:25-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c695a2a08765a6972b091688c87ba2ec61abfe4",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
