# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/gaussian_camera_config.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GaussianCameraConfigForm(object):
    def setupUi(self, GaussianCameraConfigForm):
        GaussianCameraConfigForm.setObjectName("GaussianCameraConfigForm")
        GaussianCameraConfigForm.resize(301, 261)
        self.verticalLayout = QtWidgets.QVBoxLayout(GaussianCameraConfigForm)
        self.verticalLayout.setContentsMargins(-1, 2, -1, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.roiSizeLabel = QtWidgets.QLabel(GaussianCameraConfigForm)
        self.roiSizeLabel.setObjectName("roiSizeLabel")
        self.horizontalLayout_6.addWidget(self.roiSizeLabel)
        self.roiSizeLineEdit = QtWidgets.QLineEdit(GaussianCameraConfigForm)
        self.roiSizeLineEdit.setObjectName("roiSizeLineEdit")
        self.horizontalLayout_6.addWidget(self.roiSizeLineEdit)
        spacerItem = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.spotOscillationCheckBox = QtWidgets.QCheckBox(GaussianCameraConfigForm)
        self.spotOscillationCheckBox.setObjectName("spotOscillationCheckBox")
        self.verticalLayout.addWidget(self.spotOscillationCheckBox)
        self.spotOscillationGroupBox = QtWidgets.QGroupBox(GaussianCameraConfigForm)
        self.spotOscillationGroupBox.setEnabled(False)
        self.spotOscillationGroupBox.setCheckable(False)
        self.spotOscillationGroupBox.setObjectName("spotOscillationGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.spotOscillationGroupBox)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.yAmpLabel = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.yAmpLabel.setObjectName("yAmpLabel")
        self.horizontalLayout_3.addWidget(self.yAmpLabel)
        self.yAmpLineEdit = QtWidgets.QLineEdit(self.spotOscillationGroupBox)
        self.yAmpLineEdit.setObjectName("yAmpLineEdit")
        self.horizontalLayout_3.addWidget(self.yAmpLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.xFreqLabel = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.xFreqLabel.setObjectName("xFreqLabel")
        self.horizontalLayout_2.addWidget(self.xFreqLabel)
        self.xFreqLineEdit = QtWidgets.QLineEdit(self.spotOscillationGroupBox)
        self.xFreqLineEdit.setObjectName("xFreqLineEdit")
        self.horizontalLayout_2.addWidget(self.xFreqLineEdit)
        self.xFreqUnits = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.xFreqUnits.setObjectName("xFreqUnits")
        self.horizontalLayout_2.addWidget(self.xFreqUnits)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.xAmpLabel = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.xAmpLabel.setObjectName("xAmpLabel")
        self.horizontalLayout.addWidget(self.xAmpLabel)
        self.xAmpLineEdit = QtWidgets.QLineEdit(self.spotOscillationGroupBox)
        self.xAmpLineEdit.setObjectName("xAmpLineEdit")
        self.horizontalLayout.addWidget(self.xAmpLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.yFreqLabel = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.yFreqLabel.setObjectName("yFreqLabel")
        self.horizontalLayout_4.addWidget(self.yFreqLabel)
        self.yFreqLineEdit = QtWidgets.QLineEdit(self.spotOscillationGroupBox)
        self.yFreqLineEdit.setObjectName("yFreqLineEdit")
        self.horizontalLayout_4.addWidget(self.yFreqLineEdit)
        self.yFreqUnits = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.yFreqUnits.setObjectName("yFreqUnits")
        self.horizontalLayout_4.addWidget(self.yFreqUnits)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.spotOscillationGroupBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.roiSizeLabel.setBuddy(self.roiSizeLineEdit)
        self.yAmpLabel.setBuddy(self.yAmpLineEdit)
        self.xFreqLabel.setBuddy(self.xFreqLineEdit)
        self.xAmpLabel.setBuddy(self.xAmpLineEdit)
        self.yFreqLabel.setBuddy(self.yFreqLineEdit)

        self.retranslateUi(GaussianCameraConfigForm)
        QtCore.QMetaObject.connectSlotsByName(GaussianCameraConfigForm)

    def retranslateUi(self, GaussianCameraConfigForm):
        _translate = QtCore.QCoreApplication.translate
        GaussianCameraConfigForm.setWindowTitle(_translate("GaussianCameraConfigForm", "Form"))
        self.roiSizeLabel.setText(_translate("GaussianCameraConfigForm", "ROI Size:"))
        self.spotOscillationCheckBox.setText(_translate("GaussianCameraConfigForm", "Do Spot Oscillation"))
        self.spotOscillationGroupBox.setTitle(_translate("GaussianCameraConfigForm", "Spot Oscillation Parameters"))
        self.yAmpLabel.setText(_translate("GaussianCameraConfigForm", "Y Amplitude:"))
        self.xFreqLabel.setText(_translate("GaussianCameraConfigForm", "X Frequency:"))
        self.xFreqUnits.setText(_translate("GaussianCameraConfigForm", "Hz"))
        self.xAmpLabel.setText(_translate("GaussianCameraConfigForm", "X Amplitude:"))
        self.yFreqLabel.setText(_translate("GaussianCameraConfigForm", "Y Frequency:"))
        self.yFreqUnits.setText(_translate("GaussianCameraConfigForm", "Hz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GaussianCameraConfigForm = QtWidgets.QWidget()
    ui = Ui_GaussianCameraConfigForm()
    ui.setupUi(GaussianCameraConfigForm)
    GaussianCameraConfigForm.show()
    sys.exit(app.exec_())

