
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-22T22:41:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "87b7d0235fb0b526f922f2b02796c71868235ae0",
 "version": "v2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
