
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-29T22:31:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7a9a8d7e6522344f7342385d44968ad7db1d3c3",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
