
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9e2f1bb20843d4f25eb727350957efa1101beee1",
 "version": "0.18.1.b3959"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
