
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.
from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-04-25T11:41:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c03c96520c5492fadfc438b4b0f6336e2785ba2d",
 "version": "1.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
