XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXXXXXXX X X
        XXXXX XXXXXXXXXXXXXXXXXXX
      XX
    XXXX
XXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXX
    XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXXXX
  XXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXX XXXXXXXXXXX
  XXXXXX
  XXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
 XXXXXXX
XXXXXXX
XXXXXXX