
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-22T16:24:23-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "31e97544443b743b8efe171d56d7f45c13f9568f",
 "version": "3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
