
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-17T13:34:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ccfc76db6f874c6cf8ab4b3d877752c48cfff7e",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
