XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX
  XXXXX
    XXX XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXX XXXXXXX
  XXXXXX
  XXXXX
    XXXXXXX XXXX XXXXXXX XX XXXX
    XXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXX
  XXXXXX
XXXXXX
XXXXXXX
XXXXXXX