XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXX XXXXXXXXXXXXXXX
 XXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXX XXXXXX XX XXXXXXXX
 XXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX
          XX     XXXX XX XXXXX XXXXXXX
          XX     XXXX X XXXX XX  XXXXXXX
          XXX    XXXX  XXX XXX XXXXX XXXXXX X XXXX XXXXXXX
          XXXXX  XXXX  XXX X XXXXX XXXXXX X XXXX XXXXXXX
        XXXXXX
XXXXXX
XXXXXXX
XXXXXXX