XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
   XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
     XXXXXXXXXXXXXX X X
       XXXXXX XXX XXXXXXXXXX XX XX XXX XXX XX
     XX
   XXXX
XXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
   XXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXX XXX XXX XXXXXXXXXXXX
   XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XX
   XXXX XXXXXXXXXXXXX
     XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXX
     XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXX X XXXXX XXXXXXXXXXXX
   XXXXXX
   XXXXXXXXX X  FFFFF FFFFFFFFFFXXXXXXXXXX
   XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
   XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
   XXXXXXXXXXXXXXXXX X XXXXXXXXXX
   XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
XXXXXXX
XXXXXXX
XXXXXXX