XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXX XXXXXXXXXXXXXXXX XXXXXX 
  XXXX
    XXX XXXXXXXXXXXX XX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX
      XXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXX 
      XXXX
        XXX XXXXXXXXXXXXXXX XX XXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXX XXXXXXXXXXXXXXXX XXXXXX 
        XXXXX
      XXXXX
    XXXXX
  XXXXX
XXXXXX
XXXXXXX
XXXXXXX