XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXX XX XXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


  XXXXXXXX
  XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX
    XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX

  XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX
      XX XXXX XX XXXX XX XXXXXX
      XX X XX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXX XX XXXX XXX XX X XXXXXX
                XXXXXX XXXX XX XXXX XXX XX X XXXXXX
                XXXXX XXXX XX XXXX XXXX XX X XXXXXX
            XX
         X
      XXX X XX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXX XX XXXX XXX XX XXX XXX XXXXX XXXXXX X XXXXXX
                XXXXXX XXXX XX XXXX XXX XX XXX XXX XXXXX XXXXXX X XXXXXX
                XXXXX XXXX XX XXXX XXXX XX XXX XXX XXXXX XXXXXX X XXXXXX
            XX
         X
         XXXXX XXXX XX XXXX  XXXXXX XXXXXX X
  XX

  XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX
                  XX XXXX XX XXXX XX XXXXXX
                  XX X XX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
                            XXXX XXXX XX XXXX XXX XX X XXXXXX
                            XXXXXX XXXX XX XXXX XXX XX X XXXXXX
                            XXXXX XXXX XX XXXX XXXX XX X XXXXXX
                        XX
                     X
                  XXX X XX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
                            XXXX XXXX XX XXXX XXX XX XXX XXX XXXXX XXXXXX X XXXXXX
                            XXXXXX XXXX XX XXXX XXX XX XXX XXX XXXXX XXXXXX X XXXXXX
                            XXXXX XXXX XX XXXX XXXX XX XXX XXX XXXXX XXXXXX X XXXXXX
                        XX
                     X
                     XXXXX XXXX XX XXXX  XXXXXX XXXXXX X
               XXXX
      XXXX XXX XXX XX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX  XXX XXX XXX XXXXXXXXX XX XXXXX XX XXXX
  XXXXXX
XXXXXX
XXXXXXX
XXXXXXX