
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-06T08:36:58-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "105496f8ded3c5e47961174f6f49a70d97f863c4",
 "version": "3.9.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
