XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXX
  XXXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXX X XXXXXXXX
    XXXX
XXXXXXXXX
XXXXXXX
 XXXXXXXX X
   XXXXXXXXXXXXXX XXXXXX XXXXX
   XXXXXXXXXXX XXXXXXXXXXXX
 X
 XXXXXXXXXXXXXXXXXXX X
   XXXXXXXXXXX XXXX
 X
XXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
 XXXXXXX
XXXXXXX
XXXXXXX