XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXX X XXXXX
    XXXX
XXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX
    XXXX
    XXXXXX XXXXXXXXXXXXXXXX XXXXX XXXX XX XXXXXX XX XXXXXXXXXX XX XXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXX
    XXXXXXXX XXXXX XXXX X XXXXXXXXXXXXXXXXX
    XXXXX X XXXXXXXXXXXXX
  XXXXXXX
XXXXXX
XXXXXXX
XXXXXXX