XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
  XXXX
  XXXXXXXXXX X XXXXXXXXXX
XXXXXX
XXXXXXX
XXXXXXX