XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX
    XXXXXXX
      XXXXX
      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XX
             XXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXX XX
    XXXXXXX
      XXXXX XXXXX
      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXX XX
  XXXXXXX
  XXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
XXXXXXX
XXXXXXX