# coding: utf-8

# flake8: noqa
"""
    AdvoService Integration API

    External API for AdvoService  # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: r.starenkiy@kf.ua
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from advoservice_integration.models.certificate_purchase_request import CertificatePurchaseRequest
from advoservice_integration.models.certificate_user_details import CertificateUserDetails
from advoservice_integration.models.login_detail import LoginDetail
from advoservice_integration.models.message import Message
from advoservice_integration.models.package_data import PackageData
from advoservice_integration.models.purchase_request import PurchaseRequest
from advoservice_integration.models.user_details import UserDetails
