
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-18T21:58:56-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "083e2422e63185d7d20b3dd57ae05e5d5cfc3e3b",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
