XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX X
  XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXX
  XXXXX
    XXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
  XXXXXX
  XXXXX
    XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
  XXXXXX
  XXXXX
    XXXXXXXXXXXXX  FFFFFFFF
  XXXXXX
XXXXXX
XXXXXXX
XXXXXXX