XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXX X X
       XXXXXX X XXXXX
       XXXXXX X XXXXX
     XX
    XXXX
XXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXX
  XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
   XXXXXXXXXXXXX
  XXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXX X XXXXXXXXXX
 XXXXXXX
XXXXXXX
XXXXXXX