
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-05T20:57:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1016daa62650ab28264698d55768ce516bc6cfb",
 "version": "0.1.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
