
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-27T14:09:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d9ae5b15a0cfcda7ec64bb2a3c9024633f1ffc5",
 "version": "2019.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
