XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX X
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX
  XXXXXXXXXXXXXXX
  XXXXX
    XXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X
  XXXXXX
  XXXXX
    XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
  XXXXXX
  XXXXX
    XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX
       FFFFFFFFFF
    XXXXXXXXXXX
    XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX
XXXXXXX
XXXXXXX