
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-14T05:45:14-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7871c80abbb85c0ef7482d931323f8b5866bc661",
 "version": "v0.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
