
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-24T11:15:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce7eb45b22457d5860bb2768092c5130c9dbd741",
 "version": "0.1.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
