
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-24T10:00:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f31b288c23d2fd9941f2c0cca5dc4e591cf7f8e4",
 "version": "0.6.61"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
