XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX FFFFFFFFFFFFFXXXXXXXX
    XXXXXX FFFFFFFFFFFFFXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFF FFFFFFFF FFXXXXXXXX
   XXXXXX FFFFFFFFFFFFFFFF FFFFFFFF FFXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFF F FFFFFFXXXXXXXX
   XXXXXX FFFFFFFFFFFFFFFF F FFFFFFXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFF FFFF FFFFFFXXXXXXXX
   XXXXXX FFFFFFFFFFFFFFFF FFFF FFFFFFXXXXXXXXXXX
XXXXXXX
XXXXXXX