XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
   XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
     XXXXXXXXXXXXXX X X
       XXXXXX XXX XXXXXXXXXX XX XX
     XX
   XXXX
XXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXX XX XXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
  XXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXX X XXXXX XXXXXXXXXXXXX
  XXXXXX
  XXXXXXXXX X  FFFFF FFFFFFFFFXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
XXXXXXX
XXXXXXX
XXXXXXX