XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXX XXXXX XXXXX XXX XXXXXXXX
  XXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXX XX XXXXXXXXXXXXXX
    XXXXX XXXX XXXXXXXXXXX X X X XXXXXXXXXXX  FXXXXXXXX
  XXXXXXXXXX
XXXXXXXXXX
XXXXXXX
XXXXXXX