XXXX XXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXX XXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
  XXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXXXX