XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXX X X
        XXXXXX XX
      XX
    XXXX
XXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXX XXXXXXXX XXXXXXXXX
 XXXXXXXX
  XXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXX XXXXXXXXXXXXXX
  XXXXXX
  XXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
 XXXXXXX
XXXXXXX
XXXXXXX