
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-30T10:42:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ae702c8a7107635fec9ea1c32e42f5d4e837f843",
 "version": "v1.2.0-1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
