XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXXXXXXXXX X X
        XXXXX XXXXXXXXXXXXXXXX
      XX
    XXXX
XXXXXXXXX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXX XXXXXXXXXXXXX
    XXXXXX
    XXXXXXXX X XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
    XXXXXXXXXXXXXXXXX X XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXX
XXXXXXX
XXXXXXX