
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-04T12:18:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5eb240709db22f0895a74a704449de8a9127b372",
 "version": "0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
