
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-20T14:20:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fdc0a048ab976e646cb8053628899946122384c6",
 "version": "0.0.41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
