
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "39e451a0e3651a8d136d8f33b8dbc447dd24a14f",
 "version": "1.7rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
