
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-02T11:07:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6188f3d97873f8ca0b45ae5a5d71812670ccd124",
 "version": "0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
