XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
       XXXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
       XXXXXXXXX X X XXXXXXXXX XXXXXXXXXX XX
     XXXX
XXXXXXXXX
 XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXXXXX XX XXXX XXXXXXXXXXXXXX
     XXXXXX XXXXXXXXXXXXXXX XX XXXXXX XXXXXXX
       
       XXXXXX XXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX
              XXXXX
              XXXXXXXXXXXXXXXX
     XXXXXXXX
   XXXXXXXX XXXXX XXXXXX
 XXXXXXX
XXXXXXX
XXXXXXX