
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-22T15:19:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "69ea78f6bb3ab0884d1b01fbbfbe5a4a53c8ca0f",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
