
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-04T15:13:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "35796f5b5cf8bc7810d37c3cb4397d3ae7e5847d",
 "version": "2019.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
