
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-18T10:58:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "34cfdb30fb65a58224a3c8f249bc9a3600fe673a",
 "version": "0.0.40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
