# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(here, 'README.rst'), 'r', 'utf-8') as stream:
    readme = stream.read()

setup(
    long_description=readme,
    name='dephell_venvs',
    version='0.1.10',
    description='Manage virtual environments',
    python_requires='>=3.5',
    project_urls={'repository': 'https://github.com/dephell/dephell_venvs'},
    author='Gram',
    author_email='master_fess@mail.ru',
    license='MIT',
    keywords='dephell packaging venv pipenv virtualenv',
    classifiers=[
        'Development Status :: 4 - Beta', 'Environment :: Console',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ],
    packages=['dephell_venvs'],
    package_data={},
    install_requires=['attrs', 'dephell-pythons'],
)
