#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['my_lib_test_may_2019']

package_data = \
{'': ['*']}

setup(name='my_lib_test_may_2019',
      version='0.0.1',
      description='"',
      author='Matthias Bussonnier',
      author_email='mbussonnier@ucmerced.edu',
      url='https://github.com/Carreau/my_lib_test_may_2019',
      packages=packages,
      package_data=package_data,
     )
