XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXX
    XXXX
      XXXXXXXXXXXXX
      XXXXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXXX XX XXXXXXX X XXXXXXXXXXXXXXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXXXXXX
    XXXXX
  XXXXXXXX
XXXXXX
XXXXXXX
XXXXXXX