XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
   XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXX X
        XXXXXXXXX XXXX
        XXXXXXXXXXX XXXXX
        XXXXXX X XXXXXXXXX XX
        XXXXXXXXX XXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX X
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                  XXXXXXXX
      XX
  XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX X XXXXXX XXXXXXX
    XXXXXXXXXXX X XXXXXX XXXXX XXXXXXXX XXX XXX XXXXXXX XXXXX XXXX XXXXXXXXXX
  XXXX
XXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX
  XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
XXXXXXX
XXXXXXX