XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXX
  XXXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
     XXXXXXXXXX X XXXX
   XXXX
XXXXXXXXX
XXXXXXX
  XXXXXXXXX X
    XXXXXXXXXXXXXX XXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXX
    XXXXXXXXXXX XXXX
  X
XXXXXXXX
XX XXXXXXXXXXXXXXXXXXXXXX
 XXXXXX XXXXX XX XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX
 XXXXXXX XX X XXXXX XXXXXX
XXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
XXXXXXX
XXXXXXX
XXXXXXX