
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-03T05:52:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f86691f321e3f742a0ea78073d045fc0c06c4020",
 "version": "v0.5.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
