
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-02T10:37:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e3428fbba99f4667b8d37a40a64c78160adf2389",
 "version": "1.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
