
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-04-24T11:53:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b717f1f96e127c1465301e2b7080d5599ee21d4",
 "version": "v0.14.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
