
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-19T17:28:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "746d990986b3302fdb4fccb55dbc426a6d7e9a6a",
 "version": "2019.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
