
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-25T06:34:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a501596fe0254d8f57633c667ef7ff9744b52b4",
 "version": "1.15.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
