
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-15T20:12:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "06e82d9a1ffa622b76e6700e6afe8beb6018fc07",
 "version": "0.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
