# coding: utf-8

"""
    AdvoService Integration API

    External API for AdvoService  # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: r.starenkiy@kf.ua
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import advoservice_integration
from advoservice_integration.api.purchase_api import PurchaseApi  # noqa: E501
from advoservice_integration.rest import ApiException


class TestPurchaseApi(unittest.TestCase):
    """PurchaseApi unit test stubs"""

    def setUp(self):
        self.api = advoservice_integration.api.purchase_api.PurchaseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_certificate_purchase(self):
        """Test case for add_certificate_purchase

        Register users purchase  # noqa: E501
        """
        pass

    def test_add_purchase(self):
        """Test case for add_purchase

        Register users purchase  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
