# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.models.connect_wise_manage_v2_callback import ConnectWiseManageV2Callback  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestConnectWiseManageV2Callback(unittest.TestCase):
    """ConnectWiseManageV2Callback unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectWiseManageV2Callback(self):
        """Test ConnectWiseManageV2Callback"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opsgenie_swagger.models.connect_wise_manage_v2_callback.ConnectWiseManageV2Callback()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
