# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.models.oem_email_integration import OEMEmailIntegration  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestOEMEmailIntegration(unittest.TestCase):
    """OEMEmailIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOEMEmailIntegration(self):
        """Test OEMEmailIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opsgenie_swagger.models.oem_email_integration.OEMEmailIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
