XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXX XXXXXXX XXXXX XXX XXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXXXX
XXXXXX
XXXXXXX
XXXXXXX