# This file is MACHINE GENERATED! Do not edit.
# Generated by: tensorflow/python/tools/api/generator/create_python_api.py script.
"""Public API for tf.estimator.tpu namespace.
"""

from __future__ import print_function as _print_function

from tensorflow_estimator.python.estimator.estimator_lib import TPUEstimator
from tensorflow_estimator.python.estimator.tpu.tpu_config import InputPipelineConfig
from tensorflow_estimator.python.estimator.tpu.tpu_config import RunConfig
from tensorflow_estimator.python.estimator.tpu.tpu_config import TPUConfig
from tensorflow_estimator.python.estimator.tpu.tpu_estimator import TPUEstimatorSpec

del _print_function

import sys as _sys
from tensorflow.python.util import deprecation_wrapper as _deprecation_wrapper

_DEPRECATED_TO_CANONICAL = {
    "RunConfig": "compat.v1.estimator.tpu.RunConfig",
    "TPUConfig": "compat.v1.estimator.tpu.TPUConfig",
    "TPUEstimatorSpec": "compat.v1.estimator.tpu.TPUEstimatorSpec",
    "TPUEstimator": "compat.v1.estimator.tpu.TPUEstimator",
    "InputPipelineConfig": "compat.v1.estimator.tpu.InputPipelineConfig",
}

if not isinstance(_sys.modules[__name__], _deprecation_wrapper.DeprecationWrapper):
  _sys.modules[__name__] = _deprecation_wrapper.DeprecationWrapper(
      _sys.modules[__name__], "estimator.tpu", _DEPRECATED_TO_CANONICAL)
