
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-29T09:39:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f62d6310827c387cb004fec8ee7202c62cf46a69",
 "version": "1.27.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
