# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from opsgenie_swagger.models.action_mapping import ActionMapping  # noqa: F401,E501
from opsgenie_swagger.models.alert_filter import AlertFilter  # noqa: F401,E501
from opsgenie_swagger.models.bidirectional_callback_new import BidirectionalCallbackNew  # noqa: F401,E501


class BMCRemedyCallback(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'password': 'str',
        'midtier_server_url': 'str',
        'server_name': 'str'
    }

    attribute_map = {
        'username': 'username',
        'password': 'password',
        'midtier_server_url': 'midtierServerUrl',
        'server_name': 'serverName'
    }

    def __init__(self, username=None, password=None, midtier_server_url=None, server_name=None):  # noqa: E501
        """BMCRemedyCallback - a model defined in Swagger"""  # noqa: E501

        self._username = None
        self._password = None
        self._midtier_server_url = None
        self._server_name = None
        self.discriminator = None

        if username is not None:
            self.username = username
        if password is not None:
            self.password = password
        if midtier_server_url is not None:
            self.midtier_server_url = midtier_server_url
        if server_name is not None:
            self.server_name = server_name

    @property
    def username(self):
        """Gets the username of this BMCRemedyCallback.  # noqa: E501


        :return: The username of this BMCRemedyCallback.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this BMCRemedyCallback.


        :param username: The username of this BMCRemedyCallback.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this BMCRemedyCallback.  # noqa: E501


        :return: The password of this BMCRemedyCallback.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this BMCRemedyCallback.


        :param password: The password of this BMCRemedyCallback.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def midtier_server_url(self):
        """Gets the midtier_server_url of this BMCRemedyCallback.  # noqa: E501


        :return: The midtier_server_url of this BMCRemedyCallback.  # noqa: E501
        :rtype: str
        """
        return self._midtier_server_url

    @midtier_server_url.setter
    def midtier_server_url(self, midtier_server_url):
        """Sets the midtier_server_url of this BMCRemedyCallback.


        :param midtier_server_url: The midtier_server_url of this BMCRemedyCallback.  # noqa: E501
        :type: str
        """

        self._midtier_server_url = midtier_server_url

    @property
    def server_name(self):
        """Gets the server_name of this BMCRemedyCallback.  # noqa: E501


        :return: The server_name of this BMCRemedyCallback.  # noqa: E501
        :rtype: str
        """
        return self._server_name

    @server_name.setter
    def server_name(self, server_name):
        """Sets the server_name of this BMCRemedyCallback.


        :param server_name: The server_name of this BMCRemedyCallback.  # noqa: E501
        :type: str
        """

        self._server_name = server_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BMCRemedyCallback):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
