# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from opsgenie_swagger.models.action_mapping import ActionMapping  # noqa: F401,E501
from opsgenie_swagger.models.alert_filter import AlertFilter  # noqa: F401,E501
from opsgenie_swagger.models.bmc_remedy_on_demand_callback import BMCRemedyOnDemandCallback  # noqa: F401,E501
from opsgenie_swagger.models.integration import Integration  # noqa: F401,E501
from opsgenie_swagger.models.team_meta import TeamMeta  # noqa: F401,E501


class BMCRemedyOnDemandIntegration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alert_filter': 'AlertFilter',
        'forwarding_enabled': 'bool',
        'forwarding_action_mappings': 'list[ActionMapping]',
        'callback_type': 'str',
        'url': 'str',
        'username': 'str',
        'password': 'str',
        'lastname': 'str',
        'firstname': 'str'
    }

    attribute_map = {
        'alert_filter': 'alertFilter',
        'forwarding_enabled': 'forwardingEnabled',
        'forwarding_action_mappings': 'forwardingActionMappings',
        'callback_type': 'callback-type',
        'url': 'url',
        'username': 'username',
        'password': 'password',
        'lastname': 'lastname',
        'firstname': 'firstname'
    }

    def __init__(self, alert_filter=None, forwarding_enabled=None, forwarding_action_mappings=None, callback_type=None, url=None, username=None, password=None, lastname=None, firstname=None):  # noqa: E501
        """BMCRemedyOnDemandIntegration - a model defined in Swagger"""  # noqa: E501

        self._alert_filter = None
        self._forwarding_enabled = None
        self._forwarding_action_mappings = None
        self._callback_type = None
        self._url = None
        self._username = None
        self._password = None
        self._lastname = None
        self._firstname = None
        self.discriminator = None

        if alert_filter is not None:
            self.alert_filter = alert_filter
        if forwarding_enabled is not None:
            self.forwarding_enabled = forwarding_enabled
        if forwarding_action_mappings is not None:
            self.forwarding_action_mappings = forwarding_action_mappings
        if callback_type is not None:
            self.callback_type = callback_type
        if url is not None:
            self.url = url
        if username is not None:
            self.username = username
        if password is not None:
            self.password = password
        if lastname is not None:
            self.lastname = lastname
        if firstname is not None:
            self.firstname = firstname

    @property
    def alert_filter(self):
        """Gets the alert_filter of this BMCRemedyOnDemandIntegration.  # noqa: E501


        :return: The alert_filter of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :rtype: AlertFilter
        """
        return self._alert_filter

    @alert_filter.setter
    def alert_filter(self, alert_filter):
        """Sets the alert_filter of this BMCRemedyOnDemandIntegration.


        :param alert_filter: The alert_filter of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :type: AlertFilter
        """

        self._alert_filter = alert_filter

    @property
    def forwarding_enabled(self):
        """Gets the forwarding_enabled of this BMCRemedyOnDemandIntegration.  # noqa: E501


        :return: The forwarding_enabled of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :rtype: bool
        """
        return self._forwarding_enabled

    @forwarding_enabled.setter
    def forwarding_enabled(self, forwarding_enabled):
        """Sets the forwarding_enabled of this BMCRemedyOnDemandIntegration.


        :param forwarding_enabled: The forwarding_enabled of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :type: bool
        """

        self._forwarding_enabled = forwarding_enabled

    @property
    def forwarding_action_mappings(self):
        """Gets the forwarding_action_mappings of this BMCRemedyOnDemandIntegration.  # noqa: E501


        :return: The forwarding_action_mappings of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :rtype: list[ActionMapping]
        """
        return self._forwarding_action_mappings

    @forwarding_action_mappings.setter
    def forwarding_action_mappings(self, forwarding_action_mappings):
        """Sets the forwarding_action_mappings of this BMCRemedyOnDemandIntegration.


        :param forwarding_action_mappings: The forwarding_action_mappings of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :type: list[ActionMapping]
        """

        self._forwarding_action_mappings = forwarding_action_mappings

    @property
    def callback_type(self):
        """Gets the callback_type of this BMCRemedyOnDemandIntegration.  # noqa: E501


        :return: The callback_type of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :rtype: str
        """
        return self._callback_type

    @callback_type.setter
    def callback_type(self, callback_type):
        """Sets the callback_type of this BMCRemedyOnDemandIntegration.


        :param callback_type: The callback_type of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :type: str
        """
        allowed_values = ["amazon-sns-callback", "base-webhook-callback", "bidirectional-callback-new", "bmc-remedy-on-demand-callback"]  # noqa: E501
        if callback_type not in allowed_values:
            raise ValueError(
                "Invalid value for `callback_type` ({0}), must be one of {1}"  # noqa: E501
                .format(callback_type, allowed_values)
            )

        self._callback_type = callback_type

    @property
    def url(self):
        """Gets the url of this BMCRemedyOnDemandIntegration.  # noqa: E501


        :return: The url of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this BMCRemedyOnDemandIntegration.


        :param url: The url of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def username(self):
        """Gets the username of this BMCRemedyOnDemandIntegration.  # noqa: E501


        :return: The username of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this BMCRemedyOnDemandIntegration.


        :param username: The username of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this BMCRemedyOnDemandIntegration.  # noqa: E501


        :return: The password of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this BMCRemedyOnDemandIntegration.


        :param password: The password of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def lastname(self):
        """Gets the lastname of this BMCRemedyOnDemandIntegration.  # noqa: E501


        :return: The lastname of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :rtype: str
        """
        return self._lastname

    @lastname.setter
    def lastname(self, lastname):
        """Sets the lastname of this BMCRemedyOnDemandIntegration.


        :param lastname: The lastname of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :type: str
        """

        self._lastname = lastname

    @property
    def firstname(self):
        """Gets the firstname of this BMCRemedyOnDemandIntegration.  # noqa: E501


        :return: The firstname of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname):
        """Sets the firstname of this BMCRemedyOnDemandIntegration.


        :param firstname: The firstname of this BMCRemedyOnDemandIntegration.  # noqa: E501
        :type: str
        """

        self._firstname = firstname

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BMCRemedyOnDemandIntegration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
