
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-30T13:25:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c70336512b97a0489797329d89187c4c0166fc4",
 "version": "2019.04.30.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
