
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-17T17:44:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fef4f50c20a3d6e3f71193c7b0d1fcb3dc3c9842",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
