
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-24T16:11:01-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "74d86d3ee7b4550253f92f70e1612bf3c1628274",
 "version": "1.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
