
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-24T09:13:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b0ee3bedee567f2114aee3c9517a4f062a8773e",
 "version": "0.6.59"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
