XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXXXXXXXX X XXXXXX XXXXX XXXXX XXXXXX
    XXXX
XXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXX
       XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX  XX  X X XXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXXX
XXXXXXX