
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-25T20:08:37+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "ff9a4d739bd4c5e938b2b4f4fef8acca11e59447",
 "version": "0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
