
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-20T10:12:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "853e646f7d6125977a6e1498c761b88e1304aeba",
 "version": "1.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
