
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-03T16:26:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0144b7bd3308eb7c8797e3c69d1a5385bae8446a",
 "version": "2019.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
