
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-06T17:34:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b20b6ab6031b43df245b0f5e05238fea7d1c4f0",
 "version": "2.2.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
