XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXX X
             XXXXXXXXXXXXXX X
               XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX X
               XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
               XXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X
               XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XX
           XXXX
     XXXXXXXXX
     XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
       XXXXXXX
         XXXX
           XXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXX
           XXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXX
         XXXXX
         XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXX
         XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXX XXXXXXXXX XX XXXXXXXXXX XXXXXXXX XXX XXXXXXXXX XXXXXXXXXX
           XXXX
           XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
           XXXXX
           XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXX
         XXX XXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
           XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXX
       XXXXXXXX
       XXXXXX
XXXXXXX
XXXXXXX