XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XX XXXXXXXXX XXX XXXXXXXXX XXXXXXXXX XX XXXXXXX X XXXXXXXXX
    XX XXXXXXX XXXXXXXXX XXX XXXXXXX XXXXXXXX XXXXXXX XXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
      XX XXXXXXXXX XXXXXXX XXXXXXX X XXXX XXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX X
        XXXXXXXXXXXXX
          XXXXXXXXXXXXXXX X
             XX XXXXX XXX XXXXXXXXX XXXXXXXXXX XXX XXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX
          XXXXXXXXXXXXXXX X
            XX XXXX XXX XXXXXXXXX XXXXXXXXXX XXXXXXX
            XX XXXXXX XX XXXX XXX XXXXXXX XXX
            XXXXXXXXXXXXXXXXXXXX

            XX XXXXXXX XXX XXX XXX XXX XXXX XX XX XXX XXXXXXX
            XX XXXXXX
            XX XXXXX XX XXXX XXXXXXX XXXXXXXXXXX XX XXXX
            XX XX XXXXX XXX XXXX XXXXXXXX XXXX XXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          X
        XX
      XX
    XXX
  XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXXXXX X XXXXXXXXXX
    XXXXXXXXXXX X XXXXXX XX
  XXXX
XXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXX XXXXX
  XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXX
XXXXXXX
XXXXXXX