# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from pulpcore.client.pulp_file.api_client import ApiClient


class ContentApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def content_file_files_create(self, data, **kwargs):  # noqa: E501
        """Create a file content  # noqa: E501

        ViewSet for FileContent.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.content_file_files_create(data, async=True)
        >>> result = thread.get()

        :param async bool
        :param FileContent data: (required)
        :return: FileContent
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.content_file_files_create_with_http_info(data, **kwargs)  # noqa: E501
        else:
            (data) = self.content_file_files_create_with_http_info(data, **kwargs)  # noqa: E501
            return data

    def content_file_files_create_with_http_info(self, data, **kwargs):  # noqa: E501
        """Create a file content  # noqa: E501

        ViewSet for FileContent.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.content_file_files_create_with_http_info(data, async=True)
        >>> result = thread.get()

        :param async bool
        :param FileContent data: (required)
        :return: FileContent
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method content_file_files_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `content_file_files_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '/pulp/api/v3/content/file/files/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FileContent',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def content_file_files_list(self, **kwargs):  # noqa: E501
        """List file contents  # noqa: E501

        ViewSet for FileContent.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.content_file_files_list(async=True)
        >>> result = thread.get()

        :param async bool
        :param str relative_path: Filter results where relative_path matches value
        :param str digest: Filter results where digest matches value
        :param str repository_version: Repository Version referenced by HREF
        :param str repository_version_added: Repository Version referenced by HREF
        :param str repository_version_removed: Repository Version referenced by HREF
        :param int page: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :return: InlineResponse200
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.content_file_files_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.content_file_files_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def content_file_files_list_with_http_info(self, **kwargs):  # noqa: E501
        """List file contents  # noqa: E501

        ViewSet for FileContent.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.content_file_files_list_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str relative_path: Filter results where relative_path matches value
        :param str digest: Filter results where digest matches value
        :param str repository_version: Repository Version referenced by HREF
        :param str repository_version_added: Repository Version referenced by HREF
        :param str repository_version_removed: Repository Version referenced by HREF
        :param int page: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :return: InlineResponse200
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['relative_path', 'digest', 'repository_version', 'repository_version_added', 'repository_version_removed', 'page', 'page_size']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method content_file_files_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'relative_path' in params:
            query_params.append(('relative_path', params['relative_path']))  # noqa: E501
        if 'digest' in params:
            query_params.append(('digest', params['digest']))  # noqa: E501
        if 'repository_version' in params:
            query_params.append(('repository_version', params['repository_version']))  # noqa: E501
        if 'repository_version_added' in params:
            query_params.append(('repository_version_added', params['repository_version_added']))  # noqa: E501
        if 'repository_version_removed' in params:
            query_params.append(('repository_version_removed', params['repository_version_removed']))  # noqa: E501
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '/pulp/api/v3/content/file/files/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse200',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def content_file_files_read(self, file_content_href, **kwargs):  # noqa: E501
        """Inspect a file content  # noqa: E501

        ViewSet for FileContent.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.content_file_files_read(file_content_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str file_content_href: URI of File Content. e.g.: /pulp/api/v3/content/file/files/1/ (required)
        :return: FileContent
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.content_file_files_read_with_http_info(file_content_href, **kwargs)  # noqa: E501
        else:
            (data) = self.content_file_files_read_with_http_info(file_content_href, **kwargs)  # noqa: E501
            return data

    def content_file_files_read_with_http_info(self, file_content_href, **kwargs):  # noqa: E501
        """Inspect a file content  # noqa: E501

        ViewSet for FileContent.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.content_file_files_read_with_http_info(file_content_href, async=True)
        >>> result = thread.get()

        :param async bool
        :param str file_content_href: URI of File Content. e.g.: /pulp/api/v3/content/file/files/1/ (required)
        :return: FileContent
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['file_content_href']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method content_file_files_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'file_content_href' is set
        if ('file_content_href' not in params or
                params['file_content_href'] is None):
            raise ValueError("Missing the required parameter `file_content_href` when calling `content_file_files_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_content_href' in params:
            path_params['file_content_href'] = params['file_content_href']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Basic']  # noqa: E501

        return self.api_client.call_api(
            '{file_content_href}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FileContent',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
