
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-11T10:10:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ebd2e7c269f2b3fe9613523ffa8a9fae6d693c02",
 "version": "1.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
