# coding: utf-8

"""
    AdvoService Integration API

    External API for AdvoService  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: r.starenkiy@kf.ua
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import advoservice_integration
from advoservice_integration.models.certificate_user_details import CertificateUserDetails  # noqa: E501
from advoservice_integration.rest import ApiException


class TestCertificateUserDetails(unittest.TestCase):
    """CertificateUserDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCertificateUserDetails(self):
        """Test CertificateUserDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = advoservice_integration.models.certificate_user_details.CertificateUserDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
