
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-01T16:12:54-1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "488454fe5afdf2097ae308ae988d25324ab4477e",
 "version": "v0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
