XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
       XXXXXXXXXXX X XXXXXX XXXXXXXX XXXXX XXXXXXXXXXX
     XXXX
XXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXX
    XXXXXXX
       XXXX XXXXX
       XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXX
    XXXXXX
    XXXXXXX
       XXXX XXXXX
       XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXX
    XXXXXX
  XXXXXXX
  XXXX
  XXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
XXXXXX
XXXXXXX
XXXXXXX