XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
  XXXX XXXXXXXXXXXXXX XX XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX

  XXXXXXXX XXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX
XXXXXXX
XXXXXXX