XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXX
  XXXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX
  XXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXXXXX X
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXX XX

  XXXXXXXXXXXXXXXXXXXXX X XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
  XXXXXXXXXXXXXXXXX X XXXXXX
XXXXXX
XXXXXXX
XXXXXXX