
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-20T15:05:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f26057d1e2c50b13823e03b8b32c8de2b29bac98",
 "version": "0.0.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
