# coding: utf-8

"""
    backend/api/job.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfp_job
from kfp_job.models.job_mode import JobMode  # noqa: E501
from kfp_job.rest import ApiException


class TestJobMode(unittest.TestCase):
    """JobMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobMode(self):
        """Test JobMode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kfp_job.models.job_mode.JobMode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
