# coding: utf-8

"""
    backend/api/run.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfp_run
from kfp_run.models.api_report_run_metrics_request import ApiReportRunMetricsRequest  # noqa: E501
from kfp_run.rest import ApiException


class TestApiReportRunMetricsRequest(unittest.TestCase):
    """ApiReportRunMetricsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiReportRunMetricsRequest(self):
        """Test ApiReportRunMetricsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kfp_run.models.api_report_run_metrics_request.ApiReportRunMetricsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
