# coding: utf-8

"""
    backend/api/pipeline.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfp_pipeline
from kfp_pipeline.models.api_list_pipelines_response import ApiListPipelinesResponse  # noqa: E501
from kfp_pipeline.rest import ApiException


class TestApiListPipelinesResponse(unittest.TestCase):
    """ApiListPipelinesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiListPipelinesResponse(self):
        """Test ApiListPipelinesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kfp_pipeline.models.api_list_pipelines_response.ApiListPipelinesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
