
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-21T15:02:49+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "4666daa4aa0d5a467ed1458a9e699cb649be8186",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
