XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXX XXXXXXXXXXXXXXX
   XXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXX XXXXXX XX XXXXXXXX
   XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
      XX  XXX XXX XXXXX XXX XXXXX XX XXXXXXXX
      XX X  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
             XXXXXX X  XXXX  XXX XXXXXX
             XXXX X  XXXX  XXX XXXXXX
             XXXXX X  XXXX  XXXXX XXXXXX
            XX
          X
      XXXXX  XXXX  XXXXXX XXXXXXX
      XXXXXX
XXXXXXX
XXXXXXX