
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-11T21:48:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2314f0df6498658c8a9b47feaf3ae3f5ae59ce43",
 "version": "v0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
