
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-24T14:57:19-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "df8ba070e44a9d8e6ffcb70958f851e6776e2853",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
