XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXX X X
        XXXXX XXXXXXXX
        XXXXX XXXXXXXXXXXXX
      XX
    XXXX
XXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXX XXXXXXXXXXXX
  XXXXXX
  XXXXXXXXXX X XXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
 XXXXXXX
XXXXXXX
XXXXXXX