# This file is MACHINE GENERATED! Do not edit.
# Generated by: tensorflow/python/tools/api/generator/create_python_api.py script.
"""Public API for tf.estimator.experimental namespace.
"""

from __future__ import print_function as _print_function

from tensorflow_estimator.python.estimator.canned.linear import LinearSDCA
from tensorflow_estimator.python.estimator.early_stopping import make_early_stopping_hook
from tensorflow_estimator.python.estimator.early_stopping import stop_if_higher_hook
from tensorflow_estimator.python.estimator.early_stopping import stop_if_lower_hook
from tensorflow_estimator.python.estimator.early_stopping import stop_if_no_decrease_hook
from tensorflow_estimator.python.estimator.early_stopping import stop_if_no_increase_hook
from tensorflow_estimator.python.estimator.estimator_lib import call_logit_fn
from tensorflow_estimator.python.estimator.export.export import build_raw_supervised_input_receiver_fn
from tensorflow_estimator.python.estimator.hooks.hooks import InMemoryEvaluatorHook
from tensorflow_estimator.python.estimator.hooks.hooks import make_stop_at_checkpoint_step_hook

del _print_function

import sys as _sys
from tensorflow.python.util import deprecation_wrapper as _deprecation_wrapper

_DEPRECATED_TO_CANONICAL = {
    "make_stop_at_checkpoint_step_hook": "estimator.experimental.make_stop_at_checkpoint_step_hook",
    "stop_if_no_increase_hook": "estimator.experimental.stop_if_no_increase_hook",
    "stop_if_lower_hook": "estimator.experimental.stop_if_lower_hook",
    "make_early_stopping_hook": "estimator.experimental.make_early_stopping_hook",
    "call_logit_fn": "estimator.experimental.call_logit_fn",
    "stop_if_no_decrease_hook": "estimator.experimental.stop_if_no_decrease_hook",
    "build_raw_supervised_input_receiver_fn": "estimator.experimental.build_raw_supervised_input_receiver_fn",
    "stop_if_higher_hook": "estimator.experimental.stop_if_higher_hook",
    "InMemoryEvaluatorHook": "estimator.experimental.InMemoryEvaluatorHook",
    "LinearSDCA": "estimator.experimental.LinearSDCA",
}

if not isinstance(_sys.modules[__name__], _deprecation_wrapper.DeprecationWrapper):
  _sys.modules[__name__] = _deprecation_wrapper.DeprecationWrapper(
      _sys.modules[__name__], "estimator.experimental", _DEPRECATED_TO_CANONICAL)
