
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-24T20:23:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "df664648cc5b65bc16354b52c0e68c3b62e26e35",
 "version": "2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
