#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['scikit_rest']

package_data = \
{'': ['*']}

install_requires = \
['flask==0.12.2',
 'flask-restful',
 'numpy',
 'pandas',
 'python-dateutil',
 'scikit-learn']

setup(name='scikit_rest',
      version='0.1.1',
      description='Automatically serve ML model as a REST API',
      author='Aditya Kelvianto Sidharta',
      author_email='aditya.sdrt@gmail.com',
      url='https://github.com/AdityaSidharta/scikit_rest',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
