# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GeneratorControl.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GeneratorControlMain(object):
    def setupUi(self, GeneratorControlMain):
        GeneratorControlMain.setObjectName("GeneratorControlMain")
        GeneratorControlMain.resize(1020, 920)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GeneratorControlMain.sizePolicy().hasHeightForWidth())
        GeneratorControlMain.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(GeneratorControlMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.sepLine = QtWidgets.QFrame(self.centralwidget)
        self.sepLine.setGeometry(QtCore.QRect(10, 150, 1001, 16))
        self.sepLine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sepLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.sepLine.setObjectName("sepLine")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 830, 1001, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.btnsHLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.btnsHLayout.setContentsMargins(0, 0, 0, 0)
        self.btnsHLayout.setObjectName("btnsHLayout")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.btnsHLayout.addItem(spacerItem)
        self.insideBtnsHLayout = QtWidgets.QHBoxLayout()
        self.insideBtnsHLayout.setObjectName("insideBtnsHLayout")
        self.saveBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.saveBtn.setObjectName("saveBtn")
        self.insideBtnsHLayout.addWidget(self.saveBtn)
        self.runBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.runBtn.setObjectName("runBtn")
        self.insideBtnsHLayout.addWidget(self.runBtn)
        self.exitBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.exitBtn.setObjectName("exitBtn")
        self.insideBtnsHLayout.addWidget(self.exitBtn)
        self.btnsHLayout.addLayout(self.insideBtnsHLayout)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.btnsHLayout.addItem(spacerItem1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 1001, 140))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.topHLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.topHLayout.setContentsMargins(0, 0, 0, 0)
        self.topHLayout.setObjectName("topHLayout")
        self.fileVLayout = QtWidgets.QVBoxLayout()
        self.fileVLayout.setObjectName("fileVLayout")
        self.file1HLayout = QtWidgets.QHBoxLayout()
        self.file1HLayout.setObjectName("file1HLayout")
        self.execHintLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.execHintLabel.setFont(font)
        self.execHintLabel.setObjectName("execHintLabel")
        self.file1HLayout.addWidget(self.execHintLabel)
        self.execPathEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.execPathEdit.sizePolicy().hasHeightForWidth())
        self.execPathEdit.setSizePolicy(sizePolicy)
        self.execPathEdit.setObjectName("execPathEdit")
        self.file1HLayout.addWidget(self.execPathEdit)
        self.findExecBtn = QtWidgets.QToolButton(self.layoutWidget1)
        self.findExecBtn.setObjectName("findExecBtn")
        self.file1HLayout.addWidget(self.findExecBtn)
        self.file1HLayout.setStretch(0, 3)
        self.file1HLayout.setStretch(1, 3)
        self.file1HLayout.setStretch(2, 3)
        self.fileVLayout.addLayout(self.file1HLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.fileVLayout.addItem(spacerItem2)
        self.file2HLayout = QtWidgets.QHBoxLayout()
        self.file2HLayout.setObjectName("file2HLayout")
        self.saveAsLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.saveAsLabel.setFont(font)
        self.saveAsLabel.setObjectName("saveAsLabel")
        self.file2HLayout.addWidget(self.saveAsLabel)
        self.inputPathEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.inputPathEdit.setObjectName("inputPathEdit")
        self.file2HLayout.addWidget(self.inputPathEdit)
        self.loadBtn = QtWidgets.QToolButton(self.layoutWidget1)
        self.loadBtn.setObjectName("loadBtn")
        self.file2HLayout.addWidget(self.loadBtn)
        self.fileVLayout.addLayout(self.file2HLayout)
        self.fileVLayout.setStretch(0, 3)
        self.fileVLayout.setStretch(1, 3)
        self.fileVLayout.setStretch(2, 3)
        self.topHLayout.addLayout(self.fileVLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.topHLayout.addItem(spacerItem3)
        self.logoLabel = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setObjectName("logoLabel")
        self.topHLayout.addWidget(self.logoLabel)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 170, 1001, 651))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.paramLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.paramLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramLabel.sizePolicy().hasHeightForWidth())
        self.paramLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.paramLabel.setFont(font)
        self.paramLabel.setObjectName("paramLabel")
        self.verticalLayout_2.addWidget(self.paramLabel)
        self.paramTableWidget = QtWidgets.QTableWidget(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.paramTableWidget.setFont(font)
        self.paramTableWidget.setColumnCount(6)
        self.paramTableWidget.setObjectName("paramTableWidget")
        self.paramTableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.paramTableWidget)
        GeneratorControlMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GeneratorControlMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 22))
        self.menubar.setObjectName("menubar")
        GeneratorControlMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GeneratorControlMain)
        self.statusbar.setObjectName("statusbar")
        GeneratorControlMain.setStatusBar(self.statusbar)

        self.retranslateUi(GeneratorControlMain)
        QtCore.QMetaObject.connectSlotsByName(GeneratorControlMain)
        GeneratorControlMain.setTabOrder(self.execPathEdit, self.findExecBtn)
        GeneratorControlMain.setTabOrder(self.findExecBtn, self.inputPathEdit)
        GeneratorControlMain.setTabOrder(self.inputPathEdit, self.loadBtn)
        GeneratorControlMain.setTabOrder(self.loadBtn, self.paramTableWidget)
        GeneratorControlMain.setTabOrder(self.paramTableWidget, self.saveBtn)
        GeneratorControlMain.setTabOrder(self.saveBtn, self.runBtn)
        GeneratorControlMain.setTabOrder(self.runBtn, self.exitBtn)

    def retranslateUi(self, GeneratorControlMain):
        _translate = QtCore.QCoreApplication.translate
        GeneratorControlMain.setWindowTitle(_translate("GeneratorControlMain", "MainWindow"))
        self.saveBtn.setText(_translate("GeneratorControlMain", "Save"))
        self.runBtn.setText(_translate("GeneratorControlMain", "Run"))
        self.exitBtn.setText(_translate("GeneratorControlMain", "Exit"))
        self.execHintLabel.setText(_translate("GeneratorControlMain", "Specify the generator exectutable location:"))
        self.findExecBtn.setText(_translate("GeneratorControlMain", "..."))
        self.saveAsLabel.setText(_translate("GeneratorControlMain", "Load file (leave blank if saving to a new one):"))
        self.loadBtn.setText(_translate("GeneratorControlMain", "..."))
        self.logoLabel.setText(_translate("GeneratorControlMain", "<html><head/><body><p><img src=\":/newPrefix/logo_hi_res.jpg\" width=\"220\" height=\"110\"/></p><p>                                 &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Author: Ao Liu</p></body></html>"))
        self.paramLabel.setText(_translate("GeneratorControlMain", "Table of parameters: "))

import Logo_rc
