
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-17T18:15:40-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "25055e4cc85b35f343ff5de53616f40bfca4ca73",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
