XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXX
  XXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
   XXXXXXXXXXXXXXXXXXXXXXX
   XXXX
     XXXXXXXXXXXXXX
     XXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXX
   XXXXX
XXXXXXXXXX
XXXXXXX
XXXXXXX