
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-01T18:27:56-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6292fa817f03d38fe13372a54d5b9ccd09103607",
 "version": "4.2.9b"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
