
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-05T11:24:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "734664a0ba98a08d71aa816dcdf6fa2e33be1c85",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
