
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-24T16:16:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1035cb0476f2ce5aa16218cc803f42ae1bb96898",
 "version": "1.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
