
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-25T20:38:30-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8ccdaa9a3c3633fe225c52c5ec2e014ab4c7eb01",
 "version": "0.14.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
