XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX X XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXX X XXXXXXXXXXX
      XXXXXXXXXXXXXXX X XX
      XXXXXXXXXXXXXXXXXX X XX
      XXXXXXXXXXXXXXXXXXXXXX X XX
    XXXX
XXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
     XXXXX  XXX
     XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXX XXXXXXXX  FFFFFFFFFFFFFFFFXXXX
  XXXXXXX
     XXXXX  XXX
     XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXX XXXXXXXX  FFFFFFFFFFFFFFFFFFFXXXX
  XXXXXXX
     XXXXX  XXX
     XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXX XXXX XXXXXXX  FFFFFFFFFFFFFFFFFFFFFFFXXXX
XXXXXX
XXXXXXX
XXXXXXX