XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXX
    XXXXXXXX XXXXXX
    XXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXX
    XXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

    XXXXX
      XXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XX XXXXX FFFFXXXXXX
    XXXX XX XXXXX FFFFXXXXXX
    XXXXXX XXXXXXXXXXX
  XXXXXXX
XXXXXX
XXXXXXX
XXXXXXX