# -*- coding: utf-8 -*-

"""
    testinweweewewe

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class AuthenticationResponse(object):

    """Implementation of the 'authenticationResponse' model.

    The response for authorization endpoint. accessToken model is used as base
    model

    Attributes:
        access_token (string): The access token generated after authentication
            is checked
        expires_in (float): 1 hour till token expires

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "access_token":'access_token',
        "expires_in":'expires_in'
    }

    def __init__(self,
                 access_token=None,
                 expires_in=None):
        """Constructor for the AuthenticationResponse class"""

        # Initialize members of the class
        self.access_token = access_token
        self.expires_in = expires_in


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        access_token = dictionary.get('access_token')
        expires_in = dictionary.get('expires_in')

        # Return an object of this model
        return cls(access_token,
                   expires_in)


