
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-30T20:03:57+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "374ab872fc2aa2ec0a8fe2a3f4f7c52235158f20",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
