
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-29T21:00:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c07dd2ebb1e34a73c8aead788c5ab4d1f71228bd",
 "version": "0.9.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
