XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  

  
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXX X XXXXXXX XXXXXXX XXX
        XXXXXXXXXXXXXX X XXXX
        XXXXXXXXXXXXXX X XXXX

        XXX XXXXX
        XXXXXXXXXXXX X XXXXXXXXXX X
          XX XXXXX XXXXX X XXX XXXXX XX XX XXX XXXXXXX XXXXXXXX
          XX X XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX

          XXXX X XXXXXXXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXX X X XX XXXXXXXXXXXXXX X XX X
              XXXXXXXXXXXXXX X XXXXXXXXXXXXXX X XX
              XXXXXXXXXXXXXX X XXXXXXXXXXXXXX X XX
            X XXXX X
              XXXXXXXXXXXXXXXXXXX
            X
          XX XXXXX
        XX

        XXXXXXXXXXXXXXXX X XXXXXXXXXX X
          XX XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX
            XXXX X XXXXXXXXXX
          X
        XX

        XXXXXXXXXXXXXXXXX X XXXXXXXXXX X
          XXXXXXXXXXXXXX X XXXX
          XXXXXXXXXXXXXX X XXXX
        XX

        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
          XX XXXX XXXX XXXX XXX XXXXXXXX XX XXXXXXXXX XXX
          XXXXXXXXXXXXXXXXXXX
        XXX
      XXX
    XX XXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXX
    XX XX XXXXXX XXXXXXXXX XXX XXXXXXXXXX XXXXXXX XXXXX XXX XXXXXXX XXXXXX XX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XX XXXXXX XXX XXXXXXXXX XXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX X
          XXX XXXXXXX  XX XXXX XXXXXX
              XXXXXXXXX XX XX XXXX XX XXX XXXXXX XXX XXXX XXXXXXX

          XX XXXX XX XXXXXX XXX XX
          XXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
          X

          XX XXXXX XXX XXXXXXXXXXX XXX XXXXXX XXX XX XX XXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXX X XXXXXX
            XXXXXXXXXXXXX
          XXX

          XXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXX

          XX XXXXXX XX XXX XXXXXXX XXXXXXXXX XXXXXX XXX XXXXXX XXX XXXX XX XXXXXX
          XX XX XXXXXXX XXXXXXXX XXXX XXXXX XXX XXX XXXXXXX XXX XXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX
        X
      XXXX
XXXXXXXXX

XXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    XXXXXXX XXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXXX X X XXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX X X XXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX
XXXXXXX
XXXXXXX