
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-02T11:43:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "14d1fadd4e35fc70d814442136f3969e860ef9bd",
 "version": "0.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
