#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['nondjango', 'nondjango.storages']

package_data = \
{'': ['*']}

setup(name='nondjango-storages',
      version='0.1.0',
      description='nondjango-storages - Because the API is great but dependency on Django is not.',
      author='Alan Justino da Silva',
      author_email='alan.justino@yahoo.com.br',
      url=None,
      packages=packages,
      package_data=package_data,
     )
